# Generated by Django 4.2.9 on 2024-02-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='years',
            new_name='year',
        ),
    ]
